authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("signup", views.signup, name = "signup"),
    path("signin", views.signin, name = "signin"),
    path("signout", views.signout, name = "signout"),
    path("settings", views.settings, name = "settings"),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/", include("authentication.urls")),
    path("", include("mathsolver.urls", namespace="mathsolver"))
]

mathsolver/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mathsolver'

urlpatterns = [
    path("home", views.math_problem_solver, name = "home")
]

authentication/models.py
from django.db import models

# Create your models here.

mathsolver/models.py
from django.db import models

# Create your models here.
class MathProblem(models.Model):
    latex_input = models.TextField()
    result = models.TextField()

mathsolver/forms.py
from django import forms

class MathProblemForm(forms.Form):
    latex_input = forms.CharField(widget=forms.Textarea, label="Enter an integral problem")

authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

# Create your views here.
def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        conpassword = request.POST['confirm-password']

        if password != conpassword:
            messages.error(request=request, message="Passwords did not matched!")
            return

        myuser:User = User.objects.create_user(
            username= username,
            email= email,
            password= password,
        )

        myuser.save()

        messages.success(request=request, message="Sign Up Complete! Redirecting...")

        return redirect("signin")   
    print("method is "+ request.method)

    return render(request, "signup.html")

def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request=request,username=username,password=password)

        if user is not None:
            login(request=request,user=user)
            return render(request, "index.html",{'username': user.get_username})
        else:
            messages.error(request=request, message="Bad Credentials")
            return redirect('home')
    return render(request, "signin.html")

def signout(request):
    logout(request)
    return redirect("home")

def settings(request):
    return render(request, "settings.html")

mathsolver/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import MathProblemForm
from .models import MathProblem
from sympy import symbols, Integral, simplify, latex, parse_expr, solve
from sympy.parsing.latex import parse_latex
from sympy.integrals.manualintegrate import integral_steps


def solve_latex_input(latex_input):
    x = symbols('x')

    try:
        sympy_expression = parse_expr(str(parse_latex(latex_input)), transformations='all')
        print(sympy_expression)

        # Check if the expression is an integration problem
        if isinstance(sympy_expression, Integral):
            # Perform numerical integration with the 'manual' strategy
            solution = sympy_expression.doit()
            # Extract and format the steps involved in the manual integration
            strategy_steps = integral_steps(sympy_expression, x).__str__
            # strategy_steps_to_string = [step.rule for step in strategy_steps]

            result = {
                'latex_input': latex(sympy_expression),
                'numerical_solution': solution,
                'solution_strategy': strategy_steps
            }
        else:
            result = {'error': 'Not an integration problem'}

        return result

    except Exception as e:
        print(e)
        return {'error': str(e)}

def math_problem_solver(request):
    result = None

    # test_latex_input = r'\int_{0}^{1} x^2 \,dx'
    # result = solve_latex_input(test_latex_input)
    # form = MathProblemForm()
    form = MathProblemForm()
    if request.method == 'POST':
        form = MathProblemForm(request.POST)
        if form.is_valid():
            latex_input = form.cleaned_data['latex_input']
            print("input: " + repr(latex_input))
            result = solve_latex_input(latex_input)

    return render(request, 'index.html', {'form': form, 'result': result})

templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/blog.css">
    <title>Blogs - Our Website</title>
</head>
<body>

    <header>
        <a href="" class="back-link">&larr; Back</a>
        <h1>Read Most Exciting Blogs Here....</h1>
        <p>Explore the latest articles and insights.</p>
    </header>

    <section class="blog-post first">
        <h2>Understanding the Basics of Numerical Mathematics</h2>
        <p class="meta">Published on March 15, 2023 by John Doe</p>
        <img src="/static/images/math.jpg" alt="Math">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in lacus in ligula commodo tristique.
            Quisque et aliquet leo. Sed at arcu in velit tempor tempus nec sed odio. Sed vulputate congue purus,
            in pharetra elit euismod non.
        </p>
        <a href="#" class="read-more">Read more...</a>
    </section>

    <section class="blog-post mid">
        <h2>The Future of Artificial Intelligence in Math Area</h2>
        <p class="meta">Published on March 10, 2023 by Jane Smith</p>
        <img src="/static/images/blog.png" alt="Blog">
        <p>
            Fusce id elit vel metus rhoncus mattis. Duis vel suscipit dolor. Integer nec odio. Praesent libero.
            Sed cursus ante dapibus diam. Sed nisi.
        </p>
        <a href="#" class="read-more">Read more...</a>
    </section>

    <section class="blog-post last">
        <h2>10 Tips for Effective Time Management</h2>
        <p class="meta">Published on March 5, 2023 by Alex Johnson</p>
        <img src="/static/images/cat.png" alt="Time Management">
        <p>
            Vestibulum cursus in ligula lacinia lobortis. Morbi at velit at velit auctor efficitur ut ac justo.
            Donec quam est, suscipit vel ligula sit amet, tincidunt ultrices erat.
        </p>
        <a href="#" class="read-more">Read more...</a>
    </section>

    <footer>
        <p>&copy; 2023 Your Website | Contact: info@yourwebsite.com</p>
    </footer>

</body>
</html>

templates/career.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/career.css">
    <title>Careers at Our Company</title>
</head>
<body>

    <header>
        <a href="" class="back-link">&larr; Back</a>
        <h1>Careers at Your Company</h1>
    </header>

    <section class="job-opening first">
        <h2>Software Developer</h2>
        <p>
            We are looking for a talented software developer to join our team. If you are passionate
            about coding and enjoy working on challenging projects, we'd love to hear from you.
        </p>
        <button class="apply-btn">Apply Now</button>
    </section>

    <section class="job-opening mid">
        <h2>Marketing Specialist</h2>
        <p>
            Are you a creative and strategic thinker with a background in marketing? Join our team
            and help us promote our products to a global audience.
        </p>
        <button class="apply-btn">Apply Now</button>
    </section>

    <section class="job-opening third">
        <h2>Customer Support Representative</h2>
        <p>
            We value excellent customer service. If you are a people person and enjoy helping others,
            consider joining our customer support team.
        </p>
        <button class="apply-btn">Apply Now</button>
    </section>

    <footer>
        <p>Contact us at careers@yourcompany.com</p>
    </footer>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="/static/css/index.css">
  <title>Math Solving Platform</title>
</head>

<body>
  <!-- {% for message in messages %}
  <div class = "alert alert = {{message.tags}} alert-dismissible fad show" role = "alert">
    <strong>Message</strong>{{message}}
    <button type="button", class="close" data-dismiss="alerta" aria-label="close">
    <span aria-hidden="true">&times;</span>
  </div>
  {%endfor%} -->
  <div class="navbar">
    <nav class="nav" style="margin-left: 40px;">
      <a class="nav-link active" aria-current="page" href="#">Home</a>
      <a class="nav-link" href="career.html">Career</a>
      <a class="nav-link" href="blog.html">Blogs</a>
    </nav>
    <div class="dropdown">
      <img class="dropbtn" src="/static/images/cutiemodel.jpg" alt="Avatar" width="60" height="60">
      <div class="dropdown-content">
        <a href="settings">Settings</a>
        {% if user.is_authenticated %}
        <a href="signout">Sign Out</a>
        {% else %}
        <a href="signin">Sign In</a>
        <a href="signup">Sign Up</a>
        {% endif %}
        
      </div>
      </div>
      </div>
      <section class="top">
        {% if user.is_authenticated %}
        <h1>Hello {{ username }}</h1>
        {%else%}
        <h1>Hi,</h1>
        {%endif%}
        <h4>Welcome to the Numerical Math Solving Platform</h4>
    <p>This platform is designed for students who are struggling with their maths and need help <br> <span>in solving
        complex mathematical problems.</span></p>
    </section>
    <h5 style="font-size: 30px;margin-left: 70px;margin-top: 20px;">Math Solver</h5>
    <section class="card mb-3" style="max-width: 640px; margin: 20%; margin-top: 20px;background-color: #9FBB73;">
    <div id="inputSection">
      <form method="post" action="{%url 'mathsolver:home'%}">
        {% csrf_token %}
          {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-danger" style="width: 20%; margin-left: 200px;font-family: cursive;"">
          Solve
        </button>
      </form>
      {% if result %}
      
        {% if result.error %}
          <div>{{result.error}}</div>
          <li><strong>Input: </strong> {{ result.latex_input }}</li>

        
        {% else %}
          <h2>Result</h2>
          <ul>
              <li><strong>Input:</strong> {{ result.latex_input }}</li>
              {% if result.numerical_solution %}
                  <li><strong>Numerical Solution:</strong> {{ result.numerical_solution }}</li>
              {% endif %}
              <!-- {% if result.solution_strategy %}
                  <li>
                      {{result.solution_strategy}}
                  </li>
              {% endif %} -->
            </ul>
        {% endif %}
    {% endif %}
    </section>
    <section class="head">
      <h5 style="font-size: 30px;">Popular Blogs</h5>
      <div class="grid-container" style="margin-top: 20px;">
        <div class="card mb-3" style="max-width: 540px;background-color: #EEE7DA;">
          <div class="row g-0">
            <div class="col-md-4">
            <img src="/static/images/sector.jpg" style="width: 170px;" class="img-fluid rounded-start mt-3 ms-3" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title ms-3" style="font-family: cursive;">History of Math</h5>
              <p class="card-text ms-3" style="font-family: cursive;">This is a wider card with supporting text below as
                a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-body-secondary ms-3" style="font-family: cursive;">Last updated 3
                  mins ago</small></p>
              </div>
              </div>
              </div>
              
              </div>
              <div class="card mb-3" style="max-width: 540px;background-color: #DED0B6;">
                <div class="row g-0">
                  <div class="col-md-4">
            <img src="/static/images/card.jpg" style="width: 170px;" class="img-fluid rounded-start mt-3 ms-3" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title ms-3" style="font-family: cursive;">Math is FUN!!!</h5>
              <p class="card-text ms-3" style="font-family: cursive;">This is a wider card with supporting text below as
                a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-body-secondary ms-3" style="font-family: cursive;">Last updated 30
                  mins ago</small></p>
              </div>
              </div>
              </div>
              </div>
              
              </div>
              </section>
              <section style="margin-bottom: 20px;">
                <h5 style="font-size: 30px;margin-left: 70px;margin-top: 50px;">Popular Tutorials</h5>
                <div class="video">
      <div class="card mb-3"
        style="max-width: 340px;height: 260px;margin-left: 70px; margin-top: 20px; background-color: #EFE1D1;">
        <iframe width="80%" height="200px" src="https://www.youtube.com/embed/BcOPKQAZcn0" frameborder="0"
          allowfullscreen></iframe>
        <p class="card-text"><small class="text-body-secondary" style="font-family: cursive;margin-left: 34px;">Must
            watch video...</small></p>
      </div>
      <div class="card mb-3"
        style="max-width: 340px;height: 260px;margin-left: 70px; margin-top: 20px; background-color: #EFE1D1;">
        <iframe width="80%" height="200px" src="https://www.youtube.com/embed/gf0-OEvLHG4" frameborder="0"
          allowfullscreen></iframe>
        <p class="card-text"><small class="text-body-secondary" style="font-family: cursive;margin-left: 34px;">Must
            watch video...</small></p>
      </div>
      <div class="card mb-3"
        style="max-width: 340px;height: 260px;margin-left: 70px; margin-top: 20px; background-color: #EFE1D1;">
        <iframe width="80%" height="200px" src="https://www.youtube.com/embed/fiVgwEgc-DY" frameborder="0"
          allowfullscreen></iframe>
        <p class="card-text"><small class="text-body-secondary" style="font-family: cursive;margin-left: 34px;">Must
            watch video...</small></p>
      </div>
      </div>
      </section>

  <footer>
    <div class="social-media">
      <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
      <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
      <a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a>
      <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
    </div>
    <p>Contact us at careers@yourcompany.com</p>
    </footer>

   <!-- script -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    // solve the problem
    function solveProblem() {
     const problem = document.getElementById('problem').value;
     const result = eval(problem);
     document.getElementById('result').innerHTML = 'Result: ' + result;
    }
    
    // dropdown for the profile avatar
    document.addEventListener('DOMContentLoaded', function() {
     const dropdowns = document.getElementsByClassName('dropdown');
     const dropdownArray = Array.prototype.slice.call(dropdowns, 0);
    
     dropdownArray.forEach(function(dropdown) {
        dropdown.addEventListener('mouseover', function() {
          this.getElementsByClassName('dropdown-content')[0].style.display = 'block';
        });
        dropdown.addEventListener('mouseout', function() {
          this.getElementsByClassName('dropdown-content')[0].style.display = 'none';
        });
     });
    });
    
  </script>


</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/login.css">
    <title>Login</title>
</head>
<body>
  
    <div class="flex">
        <img src="/static/images/login.png" alt="">
        <div class="login-container">
            <h2>Login</h2>
            <form action="#" method="post" id="login-form">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
    
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
    
                <button type="submit">Login</button>
            </form>
        </div>
    </div>

</body>
</html>

templates/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/settings.css">
    <title>Settings</title>
</head>
<body>
    
    <a href="" class="back-link">&larr; Back</a>
    <div class="settings-container">
        <div class="header">
            <h1 style="text-align: center ;">User Settings</h1>
        </div>

        <div class="tabs" style="margin-left: 70px;">
            <button onclick="openTab('general')">General</button>
            <button onclick="openTab('security')">Security</button>
            <button onclick="openTab('privacy')">Privacy</button>
        </div>

        <div id="general" class="tab-content"  style="margin-left: 70px;">
            <h2>General Settings</h2>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" value="" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" value="" required>

            <label for="language">Language:</label>
            <select id="language" name="language">
                <option value="english">English</option>
                <option value="spanish">Spanish</option>
                <option value="french">French</option>
            </select>
        </div>

        <div id="security" class="tab-content" style="margin-left: 70px;">
            <h2>Security Settings</h2>
            <label for="password">New Password:</label>
            <input type="password" id="password" name="password" placeholder="Enter new password">
        
            <label for="confirm-password">Confirm New Password:</label>
            <input type="password" id="confirm-password" name="confirm-password" placeholder="Confirm new password">
        
            <label for="two-factor-auth">Two-Factor Authentication:</label>
            <input type="checkbox" id="two-factor-auth" name="two-factor-auth">
        </div>

        <div id="privacy" class="tab-content" style="margin-left: 70px;">
            <h2>Privacy Settings</h2>
            <label for="profile-visibility">Profile Visibility:</label>
            <select id="profile-visibility" name="profile-visibility">
                <option value="public">Public</option>
                <option value="private">Private</option>
            </select>

            <label for="notification-preferences">Notification Preferences:</label>
            <input type="checkbox" id="notification-preferences" name="notification-preferences">
                </div>
    </div>

    <script>
        function openTab(tabName) {
            var i, tabContent;
            tabContent = document.getElementsByClassName("tab-content");
            for (i = 0; i < tabContent.length; i++) {
                tabContent[i].style.display = "none";
            }
            document.getElementById(tabName).style.display = "block";
        }
    </script>

</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/signin.css">
    <title>signin</title>
</head>

<body>

    <div class="flex">
        <img src="/static/images/signin.png" alt="">
        <div class="signin-container">
            <h2>signin</h2>
            <form action="#" method="post" id="signin-form">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>

                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>

                <button type="submit">signin</button>
            </form>
        </div>
    </div>

</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/signup.css">
    <title>signup</title>
</head>

<body>

    <div class="flex">
        <div class="signup-container">
            <h1>Register</h1>
            <form action="signup" method="post">
                {%csrf_token%}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
                <br>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
                <br>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
                <br>
                <label for="confirm-password">Confirm Password:</label>
                <input type="password" id="confirm-password" name="confirm-password" required>
                <br>
                <button type="submit">Sign Up</button>
            </form>
        </div>
        <img src="/static/images/signup.png" alt="">
    </div>



</body>

</html>